### ISSUE TITLE
Countries List - not displaying names with spaces properly.

### ISSUE THREAD

**Issue by Tallguy298** [sandlbn/TuneFinder#10]
Hi.
Firstly, thanks for a great little program.
Very easy to use and works very well with AmigaAMP.

A problem when launching the program for the second time.
When reading ENVARC:TuneFinder/countries.cfg when reading names with spaces only the 1st part appears.

![Image1](https://github.com/user-attachments/assets/d60bfbf4-d3a4-4e08-be83-6c771bf38338)

Here is my countries.cfg
`AU:Australia     `
`NZ:New Zealand   ` 
`PL:Poland        `
`US:United States `
`GB:United Kingdom`
`DE:Germany       `
`CZ:Czech         `
`JP:Japan         `
`AT:Austria       `
`FR:France        `
`CA:Canada        `
`ES:Spain         `
`SE:Sweden        `
`NO:Norway        `
`DK:Denmark       `

Thank you,
Alexander.

**Comment by sandlbn** [comment]
Thanks for reporting this was an easy fix, you can download the new release from here:: 
<img width="851" alt="Screenshot 2024-11-17 at 10 40 41 PM" src="https://github.com/user-attachments/assets/f18d4b5e-bde4-4efa-a47d-d4ec144508f3">

[https://github.com/sandlbn/TuneFinder/releases/tag/v1.1a](https://github.com/sandlbn/TuneFinder/releases/tag/v1.1a)

**Comment by sandlbn** [comment]
@Tallguy298 Have you tried the new version?

**Comment by Tallguy298** [comment]
The new change works very well, thank you.

I noticed the maximum number of internet radio stations listed is 100.
Is that by design?
I live in Australia and there are over 100 digital radio stations.
Website link ... https://www.digitalradioplus.com.au/listen

Thank you,
Alexander.

**Comment by sandlbn** [comment]
You can change that from the settings window. Click on Menu->Settings. When you set it to zero, there is no limit.

<img width="694" alt="Screenshot 2024-11-18 at 10 23 39 PM" src="https://github.com/user-attachments/assets/7c94855a-09cd-4c90-b5d0-1f3dbffc16c0">

**Comment by Tallguy298** [comment]
Works well.

Thank you.
Alexander.
