### ISSUE TITLE
Tunefinder only scans the first 49 entries of countries.cfg

### ISSUE THREAD

**Issue by Tallguy298** [sandlbn/TuneFinder#12]
Hello,
Tunefinder only scans the first 49 entries of countries.cfg.

I have 2 config files, sorted by code and by country.
When the entry for CO:Columbia is reached the position is reset.
[CLICK HERE](https://github.com/user-attachments/files/17821313/CountriesCFG.zip)

I understand that most people would not have such a huge list but it is worth noting.

Thank you...
Alexander.

**Comment by sandlbn** [comment]
There is a memory limit that prevents adding more entries to the cycle gadget. To increase the number, I could either implement autocomplete or divide it into continents and countries, resulting in two cycle gadgets. The first solution is not trivial, as it requires creating a popup, while the second solution will increase the number of fields.

**Comment by sandlbn** [comment]
Please check this version [https://github.com/sandlbn/TuneFinder/releases/tag/v1.1b](https://github.com/sandlbn/TuneFinder/releases/tag/v1.1b) It should work for a maximum of 256 entries. I tested it with your config; however, due to the space limit, you will have to limit it to 19 characters, not including the country code and separator.

**Comment by Tallguy298** [comment]
The new update works very well.
Is there a way of formatting the text so that there is no overspill if the text line is too long.
For example "`GB:United Kingdom of Great Britain and Northern Ireland (the)`" there is text outside the gadget.
I understand that you stated that the maximum length should be 19 characters but is the field font sensitive?

Thank you,
Alexander.

**Comment by sandlbn** [comment]
It depends on the font size, but I can easily add validation based on the string length and font width. If you think that approach could be sufficient, I could compile the testing version with that fix.

**Comment by sandlbn** [comment]
Please check this build. Sorry, there is no way to attach binary it to this issue. [Tunefinder-beta](https://drive.google.com/file/d/1rHkG32bhVGZPIlzhW29ZcfKa77RvJXxN/view?usp=share_link)

**Comment by Tallguy298** [comment]
On some countries the IBAN code is missing when selecting the country.
Perhaps that can be left off when display the country as it is displayed at the bottom of the GUI window when searching?

As far as font sensitivity, I understand that it probably isn't an easy thing to implement text length strings based on font size since some fonts are proportional and not fixed sized fonts.

Other than that, your beta versions works well.
Thank you again, and thanks for letting me test your test versions.

Alexander.

**Comment by sandlbn** [comment]
I think it might be possible since the font width is available when the window is created. However, when I tried modifying this object, I encountered some strange errors. Another idea could be to craft the list so that the country names do not exceed 19 characters. Please look at this file:  [Country list](https://drive.google.com/file/d/1is-SHwqMPi6Z8qmEWvParX43hkV4X6XG/view?usp=sharing)

**Comment by Tallguy298** [comment]
OK. Good idea.
Thanks,
Alexander.

**Comment by sandlbn** [comment]
Anyway, great idea with the list! I had fun exploring radios from countries around the world. It could be neat to introduce such a list with an installer or divide the list by continent, giving users the choice of which continent they want to listen to. However, cycling through 100 - 256 countries is not the best idea.

**Comment by Tallguy298** [comment]
Perhaps a preferences editor?
However most Amiga users a pretty savvy.
Editing `ENVARC:Tunefinder/countries.cfg` can be done with any old text editor.

One final thing.
Could you please insert a $VER string in your code.

Thanks,
Alexander.

**Comment by sandlbn** [comment]
There is a VERS but I could change it to VER https://github.com/sandlbn/TuneFinder/blob/9f075bf92e70e751a646c5c1e9245fe102a922b4/include/version.h#L4

**Comment by Tallguy298** [comment]
I noticed the version string.
For some strange reason when I do a hex search through the binary it does not appear.
Thank you.

**Comment by sandlbn** [comment]
I think the best approach would be to include, by default, countries where the Amiga is or was popular, such as those in Western and Central Europe, Australia, New Zealand, and the United States. If you agree, I can also include your country configuration with the full list, modified by me to ensure it does not exceed 19 characters per entry. Additionally, I will add two sentences to the AmigaGuide explaining how to use it.

I believe adding a settings window with a text editor is unnecessary, as the same can be achieved using any text editor, even ed.

**Comment by Tallguy298** [comment]
That's a great idea.
I love using my old Amiga 600.
I am so very pleased that companies like Apollo and Michael Shultz (creator of Emu68) have injected new life with new peripherals like the PiStorm etc.
Also people like yourselves who have a passion for old technology.

Thanks again...
Alexander.

**Comment by sandlbn** [comment]
Done, Thanks for help and suggestions!
