### ISSUE TITLE
Italian catalog

### ISSUE THREAD

**Issue by samo790** [sandlbn/TuneFinder#13]
Just did an italian catalog for the program, fell free to include it into the next release :-)

[TuneFinder_italiano.zip](https://github.com/user-attachments/files/17823178/TuneFinder_italiano.zip)

**Comment by sandlbn** [comment]
Thank you! Feel free to fork the repository and submit a PR. I'm also happy to include .ct files directly in the repo and build the catalogs during compilation before releasing the .lha file. I plan to work on the next version over Thanksgiving weekend. Thanks ! Here is the place where other ct files are located: https://github.com/sandlbn/TuneFinder/tree/main/assets/translation

**Comment by samo790** [comment]
I'm not very familiar with github, I think it's better if you can just do a manual submit :-)

**Comment by sandlbn** [comment]
No problem, should I put your name against contribution or samo790 will be enough?

**Comment by samo790** [comment]
There is no problem mate, you can indifferently use my nickname (samo79) or even my real name in base of the standard naming scheme you already used for your contributors :-)
My real name is wrote in my italian .ct file aniway so you can pick from it

Btw, i just did a few more fixes, attached a new version of the catalog!

[TuneFinder_italiano_fix.zip](https://github.com/user-attachments/files/17823656/TuneFinder_italiano_fix.zip)

P.S.
Tested your program on AmigaOS 4.1, works!

**Comment by samo790** [comment]
Btw, in the country list maybe you can add italian too (IT)

**Comment by sandlbn** [comment]
I have built a new version, which you can download here. https://github.com/sandlbn/TuneFinder/releases/tag/v1.1b  Please remember to delete ENVARC:TuneFinder/countries.cfg to update the country list. In the future, I might add a check to automatically overwrite the old file if it doesn't contain any user modifications.

**Comment by samo790** [comment]
Thanks, will test it ;-)

**Comment by samo790** [comment]
It seems you uploaded a wrong version of the catalog, the one in the first message....
The correct one is into the TuneFinder_italiano_fix.zip archive (a few message above)

**Comment by sandlbn** [comment]
Are you sure I tested both catalog files: 
This is the md5 of your fix:
```
% md5 ~/Downloads/TuneFinder_italiano_fix/tunefinder.catalog
MD5 (/Users/sand/Downloads/TuneFinder_italiano_fix/tunefinder.catalog) = 9e18492f51f62b9a90c3e0f54ef1cdac
```
This is the md5 from 1.1b version: 
```
% md5 ~/Downloads/TuneFinder/Catalogs/italiano/tunefinder.catalog 
MD5 (/Users/sand/Downloads/TuneFinder/Catalogs/italiano/tunefinder.catalog) = 9e18492f51f62b9a90c3e0f54ef1cdac
```
and here is the first version that you send to me: 

```
md5 ~/Downloads/TuneFinder_italiano/tunefinder_italian.ct            
MD5 (/Users/sand/Downloads/TuneFinder_italiano/tunefinder_italian.ct) = 4f8cd245084a91cd6d853e6c5557242a

```

And here is the diff of your file vs the file from 1.1b version

```
%diff  --side-by-side /Users/sand/Downloads/TuneFinder_italiano/tunefinder.catalog /Users/sand/Downloads/TuneFinder/Catalogs/italiano/tunefinder.catalog 
% echo $?
0
```

**Comment by sandlbn** [comment]
Did you have a chance to verify this file?

**Comment by samo790** [comment]
In the fixed version i was forgot a string (because i was wrongly used an old catalog descriptor)
So the fixed version is the one we should use!
Other than that, on that (ct file) i have also added a few comments here and there
