### ISSUE TITLE
Missing $VER and file naming in version 1.2b

### ISSUE THREAD

**Issue by Tallguy298** [sandlbn/TuneFinder#16]
In your final release 1.2b...
1) All the files should be renamed.
2) Although the $VER is defined in `version.h` it does not appear in your binary executable.

Regards,
Alexander.

**Comment by sandlbn** [comment]
I will have to add it as a compiler directive and make it a resident.

asm("\t.version\t\""VERSTAG"\"");

I will add it later today.

**Comment by sandlbn** [comment]
Should work now. I replaced binary release. 
<img width="491" alt="Screenshot 2024-11-24 at 4 40 17 PM" src="https://github.com/user-attachments/assets/4062259a-cdcf-4ae2-8e8b-025768bb1c97">

**Comment by sandlbn** [comment]
@Tallguy298  Did you have a chance to test it?

**Comment by Tallguy298** [comment]
Works very well.

Weird thing.
On Aminet your release TuneFinder 1.2 extracting using WinRAR 7.10 shows no directories only files.
Using LHA on WinUAE or Amiga, files extract with directories, as they should.
No real problem, probably a fault in the archiver.

Thank you.
Alexander.

**Comment by sandlbn** [comment]
It is some weird lha compatibility issue caused by the g0 flag. I spoke with folks from Aminet. They will replace the archive ASAP.
