### ISSUE TITLE
Update Italian translation for TuneFinder 1.3

### ISSUE THREAD

**Issue by sandlbn** [sandlbn/TuneFinder#23]
@samo790  Italian translation needs to be updated to include new strings from version 1.3:

Required changes:
Add translations for favorites functionality (MSG_FAVORITE, MSG_UNFAVORITE, MSG_FAVORITES)
Add translations for favorites status messages (MSG_FAVORITE_ADDED, MSG_FAVORITE_REMOVED)
Add translations for favorites error messages (MSG_FAILED_ADD_FAVORITE, MSG_FAILED_REMOVE_FAVORITE)
Update button text for "Save All" and "Save One" (MSG_SAVE, MSG_SAVE_SINGLE)

The current English strings are available in tunefinder.cd

**Comment by samo790** [comment]
Sure, attached the new update! ;-)

[TuneFinder_1.3_ITA.zip](https://github.com/user-attachments/files/17970657/TuneFinder_1.3_ITA.zip)

**Comment by sandlbn** [comment]
@samo790  Could you add those two strings? 
```
flexcat assets/translation/tunefinder.cd assets/translation/italiano/tunefinder.ct CATALOG assets/translation/italiano/tunefinder.catalog || true
assets/translation/italiano/tunefinder.ct - Warning: missing translation for identifier 'MSG_FAVORITES'
assets/translation/italiano/tunefinder.ct - Warning: missing translation for identifier 'MSG_ICONIFY'
```

**Comment by samo790** [comment]
I will update it shortly! 👍

**Comment by samo790** [comment]
Attached the new Italian catalog

[TuneFinder_ITA.zip](https://github.com/user-attachments/files/18025164/TuneFinder_ITA.zip)

**Comment by sandlbn** [comment]
Merged with https://github.com/sandlbn/TuneFinder/commit/f85f25baab1c44db048885cfa94a4041e9554763
