### ISSUE TITLE
Added iconify support

### ISSUE THREAD

**Issue by samo790** [sandlbn/TuneFinder#27]
It is a feature that eventually could be added either on the menu and/or via it own gadget on the main window

**Comment by sandlbn** [comment]
I will have to refactor MainWindow create to do it. I will try to do it before the weekend. Thanks for the idea.

**Comment by sandlbn** [comment]
@samo790  Please test the latest beta it should work now, tested on Amiga os 3.x from 3.0 to 3.9.

**Comment by sandlbn** [comment]
It is merged with https://github.com/sandlbn/TuneFinder/releases/tag/v1.3-beta2
