### ISSUE TITLE
Release archive broken 

### ISSUE THREAD

**Issue by samo790** [sandlbn/TuneFinder#34]
The release archive on github appear to be broken... 
No separare directories inside the archive and maybe some files are missed too

https://github.com/sandlbn/TuneFinder/releases/download/v1.3/TuneFinder.lha

**Comment by sandlbn** [comment]
It is a compatibility issue with lha version; I just fixed it.

**Comment by samo790** [comment]
Confirmed, we can close the ticket then :-)
